[[language]]
name = "typescript"
language-servers = ["typescript-language-server"]
auto-format = true
formatter = { command = "prettier" }

[[language]]
name = "javascript"
language-servers = ["typescript-language-server"]
auto-format = true
formatter = { command = "prettier" }

[[language]]
name = "vue"
language-servers = ["@vue/language-server"]
auto-format = true
formatter = { command = "prettier", args = ["--parser", "vue"] }

[[language]]
name = "prisma"
language-servers = ["@prisma/language-server"]
auto-format = true


[[language]]
name = "bash"
language-servers = ["bash-language-server"]
auto-format = true


[[language]]
name = "python"
language-servers = ["python-lsp-server"]
auto-format = true


[[language]]
name = "css"
auto-format = true
language-servers = ["vscode-langservers-extracted"]
formatter = { command = "prettier" }


[[language]]
name = "go"
auto-format = true
formatter = { command = "goimports" }


[[language]]
name = "yaml"
language-servers = ["yaml-language-server"]
auto-format = true
