#!/usr/bin/env bash
set -Eeuo pipefail

# 构建 FNOS 挂载管理器的单文件产物。
# 主产物写入 bin/，同时在当前目录下保留一个便携副本。

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../../.." && pwd)"
SOURCE_DIR="${SCRIPT_DIR}"
BIN_OUTPUT="${REPO_ROOT}/bin/fnos-mount-manager"
LOCAL_OUTPUT="${SCRIPT_DIR}/fnos-mount-manager.sh"

MODULES=(
  "${SOURCE_DIR}/common.sh"
  "${SOURCE_DIR}/config.sh"
  "${SOURCE_DIR}/commands/generate.sh"
  "${SOURCE_DIR}/commands/apply.sh"
  "${SOURCE_DIR}/commands/check.sh"
  "${SOURCE_DIR}/commands/status.sh"
  "${SOURCE_DIR}/commands/service.sh"
  "${SOURCE_DIR}/commands/alias.sh"
  "${SOURCE_DIR}/commands/repair.sh"
  "${SOURCE_DIR}/commands/backfill.sh"
  "${SOURCE_DIR}/commands/reconcile.sh"
  "${SOURCE_DIR}/commands/remount.sh"
  "${SOURCE_DIR}/main.sh"
)

for module in "${MODULES[@]}"; do
  if [[ ! -f "${module}" ]]; then
    printf 'Missing module: %s\n' "${module}" >&2
    exit 1
  fi
done

mkdir -p "$(dirname "${BIN_OUTPUT}")"

TMP_OUTPUT="$(mktemp)"
trap 'rm -f "${TMP_OUTPUT}"' EXIT

{
  printf '#!/usr/bin/env bash\n'
  printf 'set -Eeuo pipefail\n'
  printf '# Auto-generated by linux/fnos/fnos-mount-manager/build.sh. Do not edit directly.\n'
  printf 'FNOS_MANAGER_STANDALONE=1\n'
  for module in "${MODULES[@]}"; do
    printf '\n# --- %s ---\n' "$(basename "${module}")"
    cat "${module}"
    printf '\n'
  done
} > "${TMP_OUTPUT}"

install -m 0755 "${TMP_OUTPUT}" "${BIN_OUTPUT}"
install -m 0755 "${TMP_OUTPUT}" "${LOCAL_OUTPUT}"

printf 'Built %s\n' "${BIN_OUTPUT}"
printf 'Built %s\n' "${LOCAL_OUTPUT}"
