#!/usr/bin/env bash
set -Eeuo pipefail
# Auto-generated by linux/fnos/fnos-mount-manager/build.sh. Do not edit directly.
FNOS_MANAGER_STANDALONE=1

# --- common.sh ---
# shellcheck shell=bash

if [[ -n "${FNOS_MOUNT_MANAGER_COMMON_LOADED:-}" ]]; then
  return 0
fi
FNOS_MOUNT_MANAGER_COMMON_LOADED=1

# 输出统一的管理器日志，方便诊断 generate/apply/check/repair 流程。
fm_log() {
  local level="$1"
  shift
  printf '[fnos-mount-manager][%s] %s\n' "${level}" "$*"
}

# 输出错误并终止当前命令。
fm_die() {
  fm_log "error" "$*" >&2
  exit 1
}

# 去掉字符串前后空白，保证 CSV 选项合并结果稳定。
fm_trim() {
  local value="$1"
  value="${value#"${value%%[![:space:]]*}"}"
  value="${value%"${value##*[![:space:]]}"}"
  printf '%s' "${value}"
}

# 解析当前脚本对应的管理器目录，兼容源码入口、bin 产物和目录内副本。
fm_detect_manager_home() {
  local script_path="$1"
  local script_dir
  script_dir="$(cd "$(dirname "${script_path}")" && pwd)"
  local candidates=(
    "${script_dir}"
    "${script_dir}/../fnos-mount-manager"
    "${script_dir}/../linux/fnos/fnos-mount-manager"
  )
  local candidate

  for candidate in "${candidates[@]}"; do
    if [[ -f "${candidate}/disks.example.conf" || -f "${candidate}/build.sh" ]]; then
      (cd "${candidate}" && pwd)
      return 0
    fi
  done

  printf '%s\n' "${script_dir}"
}

# 初始化管理器根目录，允许测试通过环境变量覆写。
fm_init_environment() {
  local script_path="$1"

  if [[ -n "${FNOS_MANAGER_HOME:-}" ]]; then
    FM_MANAGER_HOME="${FNOS_MANAGER_HOME}"
  else
    FM_MANAGER_HOME="$(fm_detect_manager_home "${script_path}")"
  fi

  FM_MANAGER_BLOCK_BEGIN="# BEGIN FNOS MOUNT MANAGER"
  FM_MANAGER_BLOCK_END="# END FNOS MOUNT MANAGER"
}

# 返回示例配置文件路径。
fm_example_config_path() {
  printf '%s/disks.example.conf\n' "${FM_MANAGER_HOME}"
}

# 返回本机私有配置文件路径。
fm_local_config_path() {
  printf '%s/disks.local.conf\n' "${FM_MANAGER_HOME}"
}

# 返回示例挂载区块预览文件路径。
fm_example_fstab_path() {
  printf '%s/fstab.example\n' "${FM_MANAGER_HOME}"
}

# 返回本机挂载区块预览文件路径。
fm_local_fstab_path() {
  printf '%s/fstab\n' "${FM_MANAGER_HOME}"
}

# 返回示例 tmpfiles 预览文件路径。
fm_example_tmpfiles_path() {
  printf '%s/tmpfiles.example.conf\n' "${FM_MANAGER_HOME}"
}

# 返回本机 tmpfiles 预览文件路径。
fm_local_tmpfiles_path() {
  printf '%s/tmpfiles.conf\n' "${FM_MANAGER_HOME}"
}

# 返回源码入口路径，便于测试对照源码入口与构建产物。
fm_source_entry_path() {
  printf '%s/main.sh\n' "${FM_MANAGER_HOME}"
}

# 合并逗号分隔的挂载选项，避免重复选项污染生成结果。
fm_merge_csv_options() {
  local part
  local item
  local -a merged=()
  local -A seen=()

  for part in "$@"; do
    [[ -n "${part}" ]] || continue
    IFS=',' read -r -a items <<< "${part}"
    for item in "${items[@]}"; do
      item="$(fm_trim "${item}")"
      [[ -n "${item}" ]] || continue
      if [[ -z "${seen["${item}"]+x}" ]]; then
        seen["${item}"]=1
        merged+=("${item}")
      fi
    done
  done

  local IFS=','
  printf '%s' "${merged[*]}"
}

# 把 LABEL:/UUID: 前缀转换成 fstab 可直接使用的 source spec。
fm_source_to_spec() {
  local source="$1"
  case "${source}" in
    LABEL:*)
      printf 'LABEL=%s' "${source#LABEL:}"
      ;;
    UUID:*)
      printf 'UUID=%s' "${source#UUID:}"
      ;;
    *)
      fm_die "Unsupported disk source: ${source}"
      ;;
  esac
}

# 把 LABEL:/UUID: 前缀转换成 /dev/disk/by-* 路径，便于检查设备是否存在。
fm_source_to_device_path() {
  local source="$1"
  local device_root="${FNOS_MANAGER_DEVICE_ROOT:-/dev/disk}"
  case "${source}" in
    LABEL:*)
      printf '%s/by-label/%s' "${device_root}" "${source#LABEL:}"
      ;;
    UUID:*)
      printf '%s/by-uuid/%s' "${device_root}" "${source#UUID:}"
      ;;
    *)
      fm_die "Unsupported disk source: ${source}"
      ;;
  esac
}

# 解析设备软链接到真实块设备路径，方便 findmnt 和占用检测得到一致结果。
fm_resolve_device_path() {
  local device_path="$1"
  if command -v realpath >/dev/null 2>&1 && [[ -e "${device_path}" ]]; then
    realpath "${device_path}"
    return 0
  fi
  printf '%s\n' "${device_path}"
}

# 查找指定设备当前已经挂载到的目标路径。
fm_find_mount_target_for_device() {
  local device_path="$1"
  local resolved_device
  resolved_device="$(fm_resolve_device_path "${device_path}")"

  findmnt -rn -S "${resolved_device}" -o TARGET 2>/dev/null | head -n 1 || true
}

# 判断目标路径是否正好是一个独立挂载点，而不是仅仅位于某个已挂载父文件系统下。
fm_is_exact_mountpoint() {
  local mountpoint="$1"
  local mounted_target
  mounted_target="$(findmnt -rn -M "${mountpoint}" -o TARGET 2>/dev/null || true)"
  [[ "${mounted_target}" == "${mountpoint}" ]]
}

# 把当前磁盘配置渲染为 tmpfiles 规则，确保开机前挂载点目录已存在。
fm_render_tmpfiles_entries() {
  local i
  for (( i = 0; i < ${#FM_CONFIG_DISK_MOUNTPOINTS[@]}; i += 1 )); do
    printf 'd %s 0755 root root -\n' "${FM_CONFIG_DISK_MOUNTPOINTS[${i}]}"
  done
}

# 生成 systemd mount/automount unit 名称，优先复用 systemd-escape 以兼容空格路径。
fm_unit_name_for_path() {
  local path="$1"
  local suffix="$2"
  if command -v systemd-escape >/dev/null 2>&1; then
    systemd-escape --path "${path}" --suffix="${suffix}"
    return 0
  fi

  local escaped="${path#/}"
  escaped="${escaped//\//-}"
  printf '%s.%s\n' "${escaped}" "${suffix}"
}

# 通过 id 检查当前进程是否已经具备 root 权限。
fm_is_root() {
  [[ "$(id -u)" -eq 0 ]]
}

# 在真实系统上优先走 sudo，在测试中允许显式关闭 sudo 以驱动假命令。
fm_run_privileged() {
  if fm_is_root || [[ "${FNOS_MANAGER_TEST_NO_SUDO:-0}" == "1" ]]; then
    "$@"
    return
  fi

  if ! command -v sudo >/dev/null 2>&1; then
    fm_die "sudo is required for privileged operations"
  fi

  sudo "$@"
}

# 在任何入口里安全读取文件内容，文件不存在时返回空字符串。
fm_read_file_or_empty() {
  local path="$1"
  if [[ -f "${path}" ]]; then
    cat "${path}"
    return 0
  fi
  return 0
}

# 从目标 fstab 中提取当前受管区块，便于 check 比较当前系统状态与本地渲染是否一致。
fm_extract_managed_block() {
  local path="$1"
  [[ -f "${path}" ]] || return 0

  awk -v begin="${FM_MANAGER_BLOCK_BEGIN}" -v end="${FM_MANAGER_BLOCK_END}" '
    $0 == begin { in_block = 1 }
    in_block { print }
    $0 == end { in_block = 0 }
  ' "${path}"
}

# 把新的受管区块写回目标 fstab 内容，保留非受管条目不变。
fm_merge_managed_block() {
  local source_file="$1"
  local output_file="$2"
  local block_content="$3"

  if [[ ! -f "${source_file}" ]]; then
    printf '%s\n' "${block_content}" > "${output_file}"
    return 0
  fi

  awk -v begin="${FM_MANAGER_BLOCK_BEGIN}" -v end="${FM_MANAGER_BLOCK_END}" -v block="${block_content}" '
    BEGIN {
      in_block = 0
      replaced = 0
    }
    $0 == begin {
      if (!replaced) {
        print block
        replaced = 1
      }
      in_block = 1
      next
    }
    $0 == end {
      in_block = 0
      next
    }
    !in_block {
      print
    }
    END {
      if (!replaced) {
        if (NR > 0) {
          print ""
        }
        print block
      }
    }
  ' "${source_file}" > "${output_file}"
}

# 把普通文件安全替换到目标路径。真实系统写 /etc/fstab 时通过提权桥接完成写入。
fm_install_file() {
  local source_file="$1"
  local target_file="$2"
  local target_dir
  target_dir="$(dirname "${target_file}")"

  if [[ -w "${target_dir}" ]]; then
    local temp_target
    temp_target="$(mktemp "${target_file}.tmp.XXXXXX")"
    cp "${source_file}" "${temp_target}"
    chmod 0644 "${temp_target}"
    mv "${temp_target}" "${target_file}"
    return 0
  fi

  local temp_target="${target_file}.fnos-manager.tmp"
  fm_run_privileged sh -c '
    set -eu
    cat "$1" > "$2"
    chmod 0644 "$2"
    mv "$2" "$3"
  ' _ "${source_file}" "${temp_target}" "${target_file}"
}


# --- config.sh ---
# shellcheck shell=bash

if [[ -n "${FNOS_MOUNT_MANAGER_CONFIG_LOADED:-}" ]]; then
  return 0
fi
FNOS_MOUNT_MANAGER_CONFIG_LOADED=1

# 重置配置 DSL 的内存状态，确保每次加载配置文件前都从干净状态开始。
fm_config_reset() {
  FM_CONFIG_MOUNT_ROOT="/vol00"
  FM_CONFIG_DEFAULT_FS="ntfs"
  FM_CONFIG_DEFAULT_MODE="automount"
  FM_CONFIG_DEFAULT_OPTIONS=""
  FM_CONFIG_DEFAULT_DEVICE_TIMEOUT="60"
  FM_CONFIG_DISK_NAMES=()
  FM_CONFIG_DISK_SOURCES=()
  FM_CONFIG_DISK_MODES=()
  FM_CONFIG_DISK_FSTYPES=()
  FM_CONFIG_DISK_OPTIONS=()
  FM_CONFIG_DISK_TIMEOUTS=()
  FM_CONFIG_DISK_MOUNTPOINTS=()
}

# 配置默认挂载根目录。
mount_root() {
  FM_CONFIG_MOUNT_ROOT="$1"
}

# 配置默认文件系统类型。
default_fs() {
  FM_CONFIG_DEFAULT_FS="$1"
}

# 配置默认挂载模式。
default_mode() {
  FM_CONFIG_DEFAULT_MODE="$1"
}

# 配置默认挂载选项。
default_options() {
  FM_CONFIG_DEFAULT_OPTIONS="$1"
}

# 配置默认设备等待超时秒数。
default_device_timeout() {
  FM_CONFIG_DEFAULT_DEVICE_TIMEOUT="$1"
}

# 验证挂载模式是否属于当前脚本支持的枚举值。
fm_validate_mode() {
  local mode="$1"
  case "${mode}" in
    automount | eager)
      return 0
      ;;
    *)
      fm_die "Unsupported mount mode: ${mode}"
      ;;
  esac
}

# 验证磁盘来源是否为 LABEL:/UUID: 这两种受控格式。
fm_validate_source() {
  local source="$1"
  case "${source}" in
    LABEL:* | UUID:*)
      return 0
      ;;
    *)
      fm_die "Disk source must start with LABEL: or UUID:: ${source}"
      ;;
  esac
}

# 注册一块受管磁盘，支持针对模式、挂载点、选项和超时做按盘覆盖。
disk() {
  local name="${1:-}"
  local source="${2:-}"
  shift 2 || true

  [[ -n "${name}" ]] || fm_die "Disk name is required"
  [[ -n "${source}" ]] || fm_die "Disk source is required for disk ${name}"

  fm_validate_source "${source}"

  local mode="${FM_CONFIG_DEFAULT_MODE}"
  local fs="${FM_CONFIG_DEFAULT_FS}"
  local options=""
  local device_timeout="${FM_CONFIG_DEFAULT_DEVICE_TIMEOUT}"
  local mountpoint="${FM_CONFIG_MOUNT_ROOT}/${name}"
  local arg

  for arg in "$@"; do
    case "${arg}" in
      mode=*)
        mode="${arg#mode=}"
        ;;
      fs=*)
        fs="${arg#fs=}"
        ;;
      options=*)
        options="${arg#options=}"
        ;;
      mount=*)
        mountpoint="${arg#mount=}"
        if [[ "${mountpoint}" != /* ]]; then
          mountpoint="${FM_CONFIG_MOUNT_ROOT}/${mountpoint}"
        fi
        ;;
      device_timeout=*)
        device_timeout="${arg#device_timeout=}"
        ;;
      *)
        fm_die "Unsupported disk option for ${name}: ${arg}"
        ;;
    esac
  done

  fm_validate_mode "${mode}"

  FM_CONFIG_DISK_NAMES+=("${name}")
  FM_CONFIG_DISK_SOURCES+=("${source}")
  FM_CONFIG_DISK_MODES+=("${mode}")
  FM_CONFIG_DISK_FSTYPES+=("${fs}")
  FM_CONFIG_DISK_OPTIONS+=("${options}")
  FM_CONFIG_DISK_TIMEOUTS+=("${device_timeout}")
  FM_CONFIG_DISK_MOUNTPOINTS+=("${mountpoint}")
}

# 加载 shell 配置文件并验证磁盘定义是否完整且不重复。
fm_load_config() {
  local config_path="$1"
  [[ -f "${config_path}" ]] || fm_die "Config file not found: ${config_path}"

  fm_config_reset
  # 配置 DSL 就是管理器的用户接口，因此这里直接 source，并在事后做结构校验。
  # shellcheck disable=SC1090
  source "${config_path}"

  local disk_count="${#FM_CONFIG_DISK_NAMES[@]}"
  (( disk_count > 0 )) || fm_die "Config file does not define any disks: ${config_path}"

  local -A seen=()
  local i
  for (( i = 0; i < disk_count; i += 1 )); do
    local name="${FM_CONFIG_DISK_NAMES[${i}]}"
    if [[ -n "${seen["${name}"]+x}" ]]; then
      fm_die "Duplicate disk name detected: ${name}"
    fi
    seen["${name}"]=1
  done
}

# 返回给定索引磁盘的最终挂载选项，统一附加 automount/eager 模式所需的 systemd 选项。
fm_disk_rendered_options() {
  local index="$1"
  local base_options="${FM_CONFIG_DEFAULT_OPTIONS}"
  local disk_options="${FM_CONFIG_DISK_OPTIONS[${index}]}"
  local mode="${FM_CONFIG_DISK_MODES[${index}]}"
  local device_timeout="${FM_CONFIG_DISK_TIMEOUTS[${index}]}"
  local mode_options=""

  if [[ -n "${device_timeout}" ]]; then
    mode_options="$(fm_merge_csv_options "${mode_options}" "x-systemd.device-timeout=${device_timeout}")"
  fi

  if [[ "${mode}" == "automount" ]]; then
    mode_options="$(fm_merge_csv_options "${mode_options}" "x-systemd.automount")"
  fi

  fm_merge_csv_options "${base_options}" "${disk_options}" "${mode_options}"
}

# 把当前内存中的磁盘配置渲染成受控 fstab 区块。
fm_render_managed_block() {
  local source_label="$1"
  local i

  printf '%s\n' "${FM_MANAGER_BLOCK_BEGIN}"
  printf '# Managed by fnos-mount-manager\n'
  printf '# Source: %s\n' "${source_label}"

  for (( i = 0; i < ${#FM_CONFIG_DISK_NAMES[@]}; i += 1 )); do
    local source_spec
    source_spec="$(fm_source_to_spec "${FM_CONFIG_DISK_SOURCES[${i}]}")"
    printf '%s %s %s %s 0 0\n' \
      "${source_spec}" \
      "${FM_CONFIG_DISK_MOUNTPOINTS[${i}]}" \
      "${FM_CONFIG_DISK_FSTYPES[${i}]}" \
      "$(fm_disk_rendered_options "${i}")"
  done

  printf '%s\n' "${FM_MANAGER_BLOCK_END}"
}


# --- generate.sh ---
# shellcheck shell=bash

if [[ -n "${FNOS_MOUNT_MANAGER_GENERATE_LOADED:-}" ]]; then
  return 0
fi
FNOS_MOUNT_MANAGER_GENERATE_LOADED=1

# 把指定配置文件同时渲染为 fstab 区块预览和 tmpfiles 目录规则预览。
fm_generate_scope() {
  local config_path="$1"
  local fstab_output_path="$2"
  local tmpfiles_output_path="$3"
  local source_label="$4"

  fm_load_config "${config_path}"
  fm_render_managed_block "${source_label}" > "${fstab_output_path}"
  fm_render_tmpfiles_entries > "${tmpfiles_output_path}"
  fm_log "info" "Wrote ${fstab_output_path}"
  fm_log "info" "Wrote ${tmpfiles_output_path}"
}

# 处理 generate 子命令，默认同时更新 example 和 local 预览。
fm_cmd_generate() {
  local scope="all"

  while [[ $# -gt 0 ]]; do
    case "$1" in
      --scope)
        scope="$2"
        shift 2
        ;;
      --help | -h)
        cat <<'EOF'
Usage: fnos-mount-manager generate [--scope all|example|local]

Generate managed fstab preview blocks from shell config files.
EOF
        return 0
        ;;
      *)
        fm_die "Unknown generate option: $1"
        ;;
    esac
  done

  case "${scope}" in
    all | example)
      fm_generate_scope \
        "$(fm_example_config_path)" \
        "$(fm_example_fstab_path)" \
        "$(fm_example_tmpfiles_path)" \
        "disks.example.conf"
      ;;
  esac

  case "${scope}" in
    all | local)
      if [[ -f "$(fm_local_config_path)" ]]; then
        fm_generate_scope \
          "$(fm_local_config_path)" \
          "$(fm_local_fstab_path)" \
          "$(fm_local_tmpfiles_path)" \
          "disks.local.conf"
      elif [[ "${scope}" == "local" ]]; then
        fm_die "Local config not found: $(fm_local_config_path)"
      else
        fm_log "warn" "Skipping local generate because disks.local.conf is missing"
      fi
      ;;
  esac
}


# --- apply.sh ---
# shellcheck shell=bash

if [[ -n "${FNOS_MOUNT_MANAGER_APPLY_LOADED:-}" ]]; then
  return 0
fi
FNOS_MOUNT_MANAGER_APPLY_LOADED=1

# 检查本机预览文件是否与当前 local 配置一致，防止 apply 直接跳过 generate。
fm_assert_local_preview_is_fresh() {
  local fstab_preview_path
  local tmpfiles_preview_path
  fstab_preview_path="$(fm_local_fstab_path)"
  tmpfiles_preview_path="$(fm_local_tmpfiles_path)"
  [[ -f "${fstab_preview_path}" ]] || fm_die "Local preview is missing. Run generate first."
  [[ -f "${tmpfiles_preview_path}" ]] || fm_die "Local tmpfiles preview is missing. Run generate first."

  local temp_fstab_render
  local temp_tmpfiles_render
  temp_fstab_render="$(mktemp)"
  temp_tmpfiles_render="$(mktemp)"

  fm_generate_scope \
    "$(fm_local_config_path)" \
    "${temp_fstab_render}" \
    "${temp_tmpfiles_render}" \
    "disks.local.conf"

  if ! cmp -s "${fstab_preview_path}" "${temp_fstab_render}"; then
    rm -f "${temp_fstab_render}" "${temp_tmpfiles_render}"
    fm_die "Local preview is stale. Run generate before apply."
  fi

  if ! cmp -s "${tmpfiles_preview_path}" "${temp_tmpfiles_render}"; then
    rm -f "${temp_fstab_render}" "${temp_tmpfiles_render}"
    fm_die "Local tmpfiles preview is stale. Run generate before apply."
  fi

  rm -f "${temp_fstab_render}" "${temp_tmpfiles_render}"
}

# 确保所有受管挂载点目录存在，避免 mount 或 automount 首次触发时落到不存在路径。
fm_prepare_mountpoints() {
  local i
  for (( i = 0; i < ${#FM_CONFIG_DISK_MOUNTPOINTS[@]}; i += 1 )); do
    fm_run_privileged mkdir -p "${FM_CONFIG_DISK_MOUNTPOINTS[${i}]}"
  done
}

# 处理 apply 子命令，支持通过 --target 把受控区块写到其他 fstab 文件。
fm_cmd_apply() {
  local target="/etc/fstab"
  local tmpfiles_target="/etc/tmpfiles.d/fnos-mount-manager.conf"

  while [[ $# -gt 0 ]]; do
    case "$1" in
      --target)
        target="$2"
        shift 2
        ;;
      --tmpfiles-target)
        tmpfiles_target="$2"
        shift 2
        ;;
      --help | -h)
        cat <<'EOF'
Usage: fnos-mount-manager apply [--target /path/to/fstab] [--tmpfiles-target /path/to/tmpfiles.conf]

Merge the generated managed block into the target fstab file and optionally install tmpfiles rules.
EOF
        return 0
        ;;
      *)
        fm_die "Unknown apply option: $1"
        ;;
    esac
  done

  [[ -f "$(fm_local_config_path)" ]] || fm_die "Local config not found: $(fm_local_config_path)"
  fm_load_config "$(fm_local_config_path)"
  fm_assert_local_preview_is_fresh

  local temp_output
  temp_output="$(mktemp)"

  if [[ -f "${target}" ]]; then
    fm_merge_managed_block "${target}" "${temp_output}" "$(cat "$(fm_local_fstab_path)")"
  else
    cat "$(fm_local_fstab_path)" > "${temp_output}"
  fi

  if [[ "${target}" == "/etc/fstab" ]]; then
    fm_prepare_mountpoints
  fi

  fm_install_file "${temp_output}" "${target}"
  rm -f "${temp_output}"
  fm_log "info" "Applied managed block to ${target}"

  if [[ "${target}" == "/etc/fstab" ]]; then
    fm_install_file "$(fm_local_tmpfiles_path)" "${tmpfiles_target}"
    fm_log "info" "Applied tmpfiles rules to ${tmpfiles_target}"
  fi

  if [[ "${target}" == "/etc/fstab" ]] && command -v systemctl >/dev/null 2>&1; then
    fm_run_privileged systemctl daemon-reload
    if command -v systemd-tmpfiles >/dev/null 2>&1; then
      fm_run_privileged systemd-tmpfiles --create "${tmpfiles_target}"
    fi
  fi
}


# --- check.sh ---
# shellcheck shell=bash

if [[ -n "${FNOS_MOUNT_MANAGER_CHECK_LOADED:-}" ]]; then
  return 0
fi
FNOS_MOUNT_MANAGER_CHECK_LOADED=1

# 在受管区块不一致时输出统一 diff，方便直接看 preview 和目标文件的差异。
fm_report_managed_block_diff() {
  local expected_block="$1"
  local actual_block="$2"
  local expected_file
  local actual_file
  expected_file="$(mktemp)"
  actual_file="$(mktemp)"

  printf '%s\n' "${expected_block}" > "${expected_file}"
  printf '%s\n' "${actual_block}" > "${actual_file}"

  if command -v diff >/dev/null 2>&1; then
    local diff_output
    diff_output="$(
      diff -u \
        --label "local-preview" \
        --label "target-managed-block" \
        "${expected_file}" \
        "${actual_file}" || true
    )"
    if [[ -n "${diff_output}" ]]; then
      fm_log "error" "Managed block diff:"
      while IFS= read -r line; do
        printf '[fnos-mount-manager][error] %s\n' "${line}" >&2
      done <<< "${diff_output}"
    fi
  else
    fm_log "error" "Managed block diff: diff command not available"
    fm_log "error" "Expected block:"
    printf '%s\n' "${expected_block}" >&2
    fm_log "error" "Actual block:"
    printf '%s\n' "${actual_block}" >&2
  fi

  rm -f "${expected_file}" "${actual_file}"
}

# 检查单个渲染产物是否与当前配置匹配，并把异常累加到错误计数里。
fm_check_rendered_file() {
  local config_path="$1"
  local rendered_path="$2"
  local source_label="$3"
  local -n error_count_ref="$4"

  if [[ ! -f "${rendered_path}" ]]; then
    fm_log "error" "Rendered file is missing: ${rendered_path}"
    error_count_ref=$(( error_count_ref + 1 ))
    return 0
  fi

  local temp_render
  temp_render="$(mktemp)"

  fm_generate_scope "${config_path}" "${temp_render}" "${source_label}"

  if ! cmp -s "${rendered_path}" "${temp_render}"; then
    fm_log "error" "Rendered file is stale: ${rendered_path}"
    error_count_ref=$(( error_count_ref + 1 ))
  fi

  rm -f "${temp_render}"
}

# 检查已知的 shell 登录补挂载片段，避免把副作用留在非显式命令路径里。
fm_check_legacy_shell_mounts() {
  local mount_root="$1"
  local -n error_count_ref="$2"
  local file
  local legacy_files=(
    "/etc/profile"
    "${HOME}/.profile"
    "${HOME}/.bash_profile"
    "${HOME}/.bashrc"
  )

  for file in "${legacy_files[@]}"; do
    [[ -f "${file}" ]] || continue
    if grep -q "mount -a" "${file}" 2>/dev/null && grep -q "${mount_root}" "${file}" 2>/dev/null; then
      fm_log "error" "Legacy shell mount logic detected in ${file}"
      error_count_ref=$(( error_count_ref + 1 ))
    fi
  done
}

# 检查遗留的 force-remount systemd 服务是否仍指向旧脚本路径。
fm_check_legacy_service() {
  local -n error_count_ref="$1"

  if ! command -v systemctl >/dev/null 2>&1; then
    return 0
  fi

  local load_state
  load_state="$(systemctl show force-remount-disks.service -p LoadState --value 2>/dev/null || true)"
  [[ -n "${load_state}" && "${load_state}" != "not-found" ]] || return 0

  if systemctl cat force-remount-disks.service 2>/dev/null | grep -q "linux/fnos/remount.sh"; then
    fm_log "error" "Legacy force-remount-disks.service still points to linux/fnos/remount.sh"
    error_count_ref=$(( error_count_ref + 1 ))
  fi
}

# 处理 check 子命令，覆盖配置漂移、设备存在性、目标 fstab 状态和遗留冲突来源。
fm_cmd_check() {
  local target="/etc/fstab"
  local error_count=0

  while [[ $# -gt 0 ]]; do
    case "$1" in
      --target)
        target="$2"
        shift 2
        ;;
      --help | -h)
        cat <<'EOF'
Usage: fnos-mount-manager check [--target /path/to/fstab]

Validate generated previews, device presence, managed block drift, and known legacy conflicts.
EOF
        return 0
        ;;
      *)
        fm_die "Unknown check option: $1"
        ;;
    esac
  done

  fm_check_rendered_file "$(fm_example_config_path)" "$(fm_example_fstab_path)" "disks.example.conf" error_count

  if [[ -f "$(fm_local_config_path)" ]]; then
    fm_check_rendered_file "$(fm_local_config_path)" "$(fm_local_fstab_path)" "disks.local.conf" error_count
    fm_load_config "$(fm_local_config_path)"

    local i
    for (( i = 0; i < ${#FM_CONFIG_DISK_SOURCES[@]}; i += 1 )); do
      local source_path
      source_path="$(fm_source_to_device_path "${FM_CONFIG_DISK_SOURCES[${i}]}")"
      if [[ ! -e "${source_path}" ]]; then
        fm_log "error" "Disk source is missing for ${FM_CONFIG_DISK_NAMES[${i}]}: ${source_path}"
        error_count=$(( error_count + 1 ))
      fi
    done

    if [[ -f "${target}" ]]; then
      local expected_block
      expected_block="$(cat "$(fm_local_fstab_path)")"
      local actual_block
      actual_block="$(fm_extract_managed_block "${target}")"

      if [[ "${expected_block}" != "${actual_block}" ]]; then
        fm_log "error" "Managed block in ${target} does not match the local preview"
        fm_report_managed_block_diff "${expected_block}" "${actual_block}"
        error_count=$(( error_count + 1 ))
      fi
    else
      fm_log "error" "Target fstab does not exist: ${target}"
      error_count=$(( error_count + 1 ))
    fi

    fm_check_legacy_shell_mounts "${FM_CONFIG_MOUNT_ROOT}" error_count
  else
    fm_log "warn" "Local config is missing. Skipping local-only checks."
  fi

  fm_check_legacy_service error_count

  if (( error_count > 0 )); then
    fm_die "Check failed with ${error_count} issue(s)"
  fi

  fm_log "info" "Check passed"
}


# --- status.sh ---
# shellcheck shell=bash

if [[ -n "${FNOS_MOUNT_MANAGER_STATUS_LOADED:-}" ]]; then
  return 0
fi
FNOS_MOUNT_MANAGER_STATUS_LOADED=1

# 输出单块受管磁盘的配置与当前系统状态，供人工排障使用。
fm_print_disk_status() {
  local index="$1"
  local name="${FM_CONFIG_DISK_NAMES[${index}]}"
  local source="${FM_CONFIG_DISK_SOURCES[${index}]}"
  local mountpoint="${FM_CONFIG_DISK_MOUNTPOINTS[${index}]}"
  local mode="${FM_CONFIG_DISK_MODES[${index}]}"
  local device_path
  device_path="$(fm_source_to_device_path "${source}")"
  local mounted_target=""
  mounted_target="$(fm_find_mount_target_for_device "${device_path}" || true)"

  printf '%s\n' "${name}"
  printf '  source: %s\n' "${source}"
  printf '  mountpoint: %s\n' "${mountpoint}"
  printf '  mode: %s\n' "${mode}"
  printf '  device_path: %s\n' "${device_path}"
  printf '  device_exists: %s\n' "$([[ -e "${device_path}" ]] && printf 'yes' || printf 'no')"
  printf '  mounted: %s\n' "$([[ -n "${mounted_target}" && "${mounted_target}" == "${mountpoint}" ]] && printf 'yes' || printf 'no')"
  if [[ -n "${mounted_target}" && "${mounted_target}" != "${mountpoint}" ]]; then
    printf '  mounted_elsewhere: %s\n' "${mounted_target}"
  fi

  if command -v systemctl >/dev/null 2>&1; then
    local mount_unit
    mount_unit="$(fm_unit_name_for_path "${mountpoint}" mount)"
    printf '  mount_unit: %s\n' "${mount_unit}"
    printf '  mount_state: %s\n' "$(systemctl show "${mount_unit}" -p ActiveState --value 2>/dev/null || printf 'unknown')"

    if [[ "${mode}" == "automount" ]]; then
      local automount_unit
      automount_unit="$(fm_unit_name_for_path "${mountpoint}" automount)"
      printf '  automount_unit: %s\n' "${automount_unit}"
      printf '  automount_state: %s\n' "$(systemctl show "${automount_unit}" -p ActiveState --value 2>/dev/null || printf 'unknown')"
    fi
  fi
}

# 处理 status 子命令，展示当前机器对受管磁盘的解析结果。
fm_cmd_status() {
  local config_path
  if [[ -f "$(fm_local_config_path)" ]]; then
    config_path="$(fm_local_config_path)"
  else
    config_path="$(fm_example_config_path)"
  fi

  while [[ $# -gt 0 ]]; do
    case "$1" in
      --help | -h)
        cat <<'EOF'
Usage: fnos-mount-manager status

Show the current status of managed disks, mountpoints, and systemd units.
EOF
        return 0
        ;;
      *)
        fm_die "Unknown status option: $1"
        ;;
    esac
  done

  fm_load_config "${config_path}"

  local i
  for (( i = 0; i < ${#FM_CONFIG_DISK_NAMES[@]}; i += 1 )); do
    fm_print_disk_status "${i}"
  done
}


# --- repair.sh ---
# shellcheck shell=bash

if [[ -n "${FNOS_MOUNT_MANAGER_REPAIR_LOADED:-}" ]]; then
  return 0
fi
FNOS_MOUNT_MANAGER_REPAIR_LOADED=1

# 检查旧的 force-remount service 是否仍指向已废弃脚本。
fm_legacy_service_uses_old_script() {
  command -v systemctl >/dev/null 2>&1 || return 1
  systemctl cat force-remount-disks.service 2>/dev/null | grep -q "linux/fnos/remount.sh"
}

# 对单块受管磁盘执行统一修复：刷新 unit、确保目录存在、按挂载点重试。
fm_repair_disk() {
  local index="$1"
  local force_mode="$2"
  local name="${FM_CONFIG_DISK_NAMES[${index}]}"
  local source="${FM_CONFIG_DISK_SOURCES[${index}]}"
  local mountpoint="${FM_CONFIG_DISK_MOUNTPOINTS[${index}]}"
  local mode="${FM_CONFIG_DISK_MODES[${index}]}"
  local device_path
  device_path="$(fm_source_to_device_path "${source}")"
  local mounted_target=""
  mounted_target="$(fm_find_mount_target_for_device "${device_path}")"

  if [[ -n "${mounted_target}" && "${mounted_target}" != "${mountpoint}" ]]; then
    fm_log "warn" "${name} device is already mounted at ${mounted_target}"
    return 1
  fi

  fm_run_privileged mkdir -p "${mountpoint}"

  if command -v systemctl >/dev/null 2>&1; then
    local mount_unit
    mount_unit="$(fm_unit_name_for_path "${mountpoint}" mount)"
    fm_run_privileged systemctl reset-failed "${mount_unit}" >/dev/null 2>&1 || true

    if [[ "${mode}" == "automount" ]]; then
      local automount_unit
      automount_unit="$(fm_unit_name_for_path "${mountpoint}" automount)"
      fm_run_privileged systemctl reset-failed "${automount_unit}" >/dev/null 2>&1 || true

      if [[ "${force_mode}" == "1" ]]; then
        fm_run_privileged systemctl stop "${automount_unit}" >/dev/null 2>&1 || true
      fi
      fm_run_privileged systemctl start "${automount_unit}" >/dev/null 2>&1 || true
    fi

    if [[ "${force_mode}" == "1" ]]; then
      fm_run_privileged systemctl stop "${mount_unit}" >/dev/null 2>&1 || true
    fi
  fi

  if [[ "${force_mode}" == "1" ]]; then
    if command -v fuser >/dev/null 2>&1 && [[ -e "${device_path}" ]]; then
      fm_run_privileged fuser -k -9 "${device_path}" >/dev/null 2>&1 || true
    fi
  fi

  if fm_run_privileged mount "${mountpoint}" >/dev/null 2>&1; then
    fm_log "info" "Mounted ${mountpoint}"
    return 0
  fi

  fm_log "warn" "Mount retry failed for ${mountpoint}"
  return 1
}

# 处理 repair 子命令，默认走安全恢复路径，只有 --force 才执行破坏性步骤。
fm_cmd_repair() {
  local force_mode="0"

  while [[ $# -gt 0 ]]; do
    case "$1" in
      --force)
        force_mode="1"
        shift
        ;;
      --help | -h)
        cat <<'EOF'
Usage: fnos-mount-manager repair [--force]

Repair managed mountpoints. Default mode is non-destructive.
EOF
        return 0
        ;;
      *)
        fm_die "Unknown repair option: $1"
        ;;
    esac
  done

  [[ -f "$(fm_local_config_path)" ]] || fm_die "Local config not found: $(fm_local_config_path)"
  fm_load_config "$(fm_local_config_path)"

  if command -v systemctl >/dev/null 2>&1; then
    fm_run_privileged systemctl daemon-reload
    if [[ "${force_mode}" == "1" ]] && fm_legacy_service_uses_old_script; then
      fm_run_privileged systemctl disable --now force-remount-disks.service >/dev/null 2>&1 || true
      fm_log "warn" "Disabled legacy force-remount-disks.service"
    fi
  fi

  local failures=0
  local i
  for (( i = 0; i < ${#FM_CONFIG_DISK_NAMES[@]}; i += 1 )); do
    if ! fm_repair_disk "${i}" "${force_mode}"; then
      failures=$(( failures + 1 ))
    fi
  done

  if (( failures > 0 )); then
    fm_die "Repair completed with ${failures} mount failure(s)"
  fi

  fm_log "info" "Repair completed successfully"
}


# --- main.sh ---
#!/usr/bin/env bash
set -Eeuo pipefail

# 源码入口在开发阶段直接执行，构建产物则通过 FNOS_MANAGER_STANDALONE 避免再次 source 模块。
if [[ -z "${FNOS_MANAGER_STANDALONE:-}" ]]; then
  SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
  # shellcheck source=linux/fnos/fnos-mount-manager/common.sh
  source "${SCRIPT_DIR}/common.sh"
  # shellcheck source=linux/fnos/fnos-mount-manager/config.sh
  source "${SCRIPT_DIR}/config.sh"
  # shellcheck source=linux/fnos/fnos-mount-manager/commands/generate.sh
  source "${SCRIPT_DIR}/commands/generate.sh"
  # shellcheck source=linux/fnos/fnos-mount-manager/commands/apply.sh
  source "${SCRIPT_DIR}/commands/apply.sh"
  # shellcheck source=linux/fnos/fnos-mount-manager/commands/check.sh
  source "${SCRIPT_DIR}/commands/check.sh"
  # shellcheck source=linux/fnos/fnos-mount-manager/commands/status.sh
  source "${SCRIPT_DIR}/commands/status.sh"
  # shellcheck source=linux/fnos/fnos-mount-manager/commands/repair.sh
  source "${SCRIPT_DIR}/commands/repair.sh"
fi

# 输出统一帮助信息，说明配置路径和常用命令。
fm_show_help() {
  cat <<'EOF'
Usage: fnos-mount-manager <command> [options]

Commands:
  generate    Generate managed fstab preview blocks
  apply       Merge the local managed block into a target fstab
  check       Validate config drift and known conflicts
  status      Show current disk and unit status
  repair      Attempt a unified mount repair
  help        Show this help
EOF
}

# 按子命令分发管理器行为，保持命令面稳定。
fm_main() {
  fm_init_environment "${BASH_SOURCE[0]}"

  local command="${1:-help}"
  shift || true

  case "${command}" in
    generate)
      fm_cmd_generate "$@"
      ;;
    apply)
      fm_cmd_apply "$@"
      ;;
    check)
      fm_cmd_check "$@"
      ;;
    status)
      fm_cmd_status "$@"
      ;;
    repair)
      fm_cmd_repair "$@"
      ;;
    help | --help | -h)
      fm_show_help
      ;;
    *)
      fm_die "Unknown command: ${command}"
      ;;
  esac
}

if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
  fm_main "$@"
fi

