import { afterEach, describe, expect, it } from 'vitest'
import {
  cleanupWorkspace,
  createWorkspace,
  readText,
  runBuild,
} from './test-utils'

const workspaces: ReturnType<typeof createWorkspace>[] = []

afterEach(() => {
  while (workspaces.length > 0) {
    const workspace = workspaces.pop()
    if (workspace) {
      cleanupWorkspace(workspace)
    }
  }
})

describe('systemd service manager build', () => {
  it('produces portable outputs with the generated banner', async () => {
    const workspace = createWorkspace()
    workspaces.push(workspace)

    const result = await runBuild(workspace)

    expect(result.exitCode).toBe(0)
    expect(readText(workspace.builtBin)).toContain(
      '# Auto-generated by scripts/bash/systemd-service-manager/build.sh.',
    )
    expect(readText(workspace.builtLocal)).toContain(
      '# Auto-generated by scripts/bash/systemd-service-manager/build.sh.',
    )
  })
})
