"""Coding Plan window warmer 常量。"""

DEFAULT_CONFIG_NAME = "window-warmer.toml"
DEFAULT_TARGET_NAME = "z-ai-coding-plan"
DEFAULT_TARGET_BASE_URL = "https://open.bigmodel.cn/api/coding/paas/v4"
DEFAULT_HEALTH_PATH = "/models"
DEFAULT_POLL_SECONDS = 60
DEFAULT_REQUEST_TIMEOUT_SECONDS = 30
DEFAULT_JITTER_SECONDS = 120
DEFAULT_RETRY_COUNT = 1
DEFAULT_RETRY_DELAY_SECONDS = 30
MAX_SLEEP_CHUNK_SECONDS = 60
