-- Hammerspoon Configuration
-- Auto-generated by load_scripts.zsh
-- 自动生成的 Hammerspoon 配置入口。

hs.logger.defaultLogLevel = "info"

local log = hs.logger.new("main", "info")
local configDir = hs.configdir
local scriptsDir = configDir .. "/scripts"
local pluginsDir = scriptsDir .. "/plugins"
local pluginOrder = {
	"win-hotkeys",
	"power-lid-sleep",
}

-- 创建脚本目录。
-- 入参：无。
-- 返回值：无。
local function ensureScriptsDir()
	local scriptsPath = hs.fs.pathToAbsolute(scriptsDir)
	if not scriptsPath then
		hs.fs.mkdir(scriptsDir)
		log.i("创建 scripts 目录: " .. scriptsDir)
	end
end

-- 判断对象是否为 Lua 表。
-- 入参：value 任意 Lua 值。
-- 返回值：布尔值，true 表示 value 是 table。
local function isTable(value)
	return type(value) == "table"
end

-- 判断配置表是否为数组式列表。
-- 入参：value 任意 Lua 值。
-- 返回值：布尔值，true 表示 value 是连续数字索引表。
local function isList(value)
	if not isTable(value) then
		return false
	end

	local count = 0
	for key, _ in pairs(value) do
		if type(key) ~= "number" then
			return false
		end
		count = count + 1
	end

	if count == 0 then
		return false
	end

	for index = 1, count do
		if value[index] == nil then
			return false
		end
	end

	return true
end

-- 合并两个配置表。
-- 入参：base 默认配置表；override 覆盖配置表。
-- 返回值：合并后的新配置表。
local function mergeConfig(base, override)
	local result = {}

	for key, value in pairs(base or {}) do
		if isTable(value) then
			result[key] = mergeConfig(value, {})
		else
			result[key] = value
		end
	end

	for key, value in pairs(override or {}) do
		if isList(value) then
			result[key] = mergeConfig(value, {})
		elseif isTable(value) and isTable(result[key]) and not isList(result[key]) then
			result[key] = mergeConfig(result[key], value)
		elseif isTable(value) then
			result[key] = mergeConfig(value, {})
		else
			result[key] = value
		end
	end

	return result
end

-- 安全加载 Lua 配置文件。
-- 入参：path 文件路径；required 是否必须存在。
-- 返回值：加载成功时返回配置表；失败或不存在时返回空表。
local function loadConfigFile(path, required)
	local absolutePath = hs.fs.pathToAbsolute(path)
	if not absolutePath then
		if required then
			log.e("缺少配置文件: " .. path)
		end
		return {}
	end

	local success, loaded = pcall(dofile, absolutePath)
	if not success then
		log.e("配置加载失败: " .. path .. " - " .. tostring(loaded))
		return {}
	end

	if loaded == nil then
		return {}
	end

	if not isTable(loaded) then
		log.e("配置必须返回 table: " .. path)
		return {}
	end

	return loaded
end

-- 加载默认配置和本机覆盖配置。
-- 入参：无。
-- 返回值：合并后的配置表。
local function loadConfig()
	local defaultConfig = loadConfigFile(configDir .. "/config.lua", true)
	local localConfig = loadConfigFile(configDir .. "/config.local.lua", false)
	return mergeConfig(defaultConfig, localConfig)
end

-- 加载插件入口。
-- 入参：pluginId 插件目录名。
-- 返回值：成功时返回插件表；失败时返回 nil。
local function loadPlugin(pluginId)
	local pluginPath = pluginsDir .. "/" .. pluginId .. "/plugin.lua"
	local absolutePath = hs.fs.pathToAbsolute(pluginPath)
	if not absolutePath then
		log.e("缺少插件文件: " .. pluginPath)
		return nil
	end

	local success, plugin = pcall(dofile, absolutePath)
	if not success then
		log.e("插件加载失败: " .. pluginId .. " - " .. tostring(plugin))
		return nil
	end

	if not isTable(plugin) then
		log.e("插件必须返回 table: " .. pluginId)
		return nil
	end

	if plugin.id ~= nil and plugin.id ~= pluginId then
		log.e(string.format("插件 id 不匹配: 目录=%s, 插件=%s", pluginId, tostring(plugin.id)))
		return nil
	end

	return plugin
end

-- 合并插件默认配置和用户配置。
-- 入参：plugin 插件表；pluginId 插件目录名；globalConfig 全局配置表。
-- 返回值：插件运行配置表。
local function buildPluginConfig(plugin, pluginId, globalConfig)
	local defaultConfig = {}
	if isTable(plugin.defaultConfig) then
		defaultConfig = plugin.defaultConfig
	end

	local pluginConfigs = globalConfig.plugins or {}
	local userConfig = pluginConfigs[pluginId] or {}
	return mergeConfig(defaultConfig, userConfig)
end

-- 启动插件。
-- 入参：pluginId 插件目录名；globalConfig 全局配置表。
-- 返回值：布尔值，true 表示启动成功。
local function startPlugin(pluginId, globalConfig)
	local plugin = loadPlugin(pluginId)
	if not plugin then
		return false
	end

	local pluginConfig = buildPluginConfig(plugin, pluginId, globalConfig)
	if pluginConfig.enabled == false then
		log.i("插件已关闭: " .. pluginId)
		return true
	end

	if type(plugin.start) ~= "function" then
		log.e("插件缺少 start 函数: " .. pluginId)
		return false
	end

	local context = {
		id = pluginId,
		config = pluginConfig,
		globalConfig = globalConfig,
		configDir = configDir,
		scriptsDir = scriptsDir,
		pluginsDir = pluginsDir,
		log = hs.logger.new(pluginId, "info"),
	}

	local success, result = pcall(plugin.start, context)
	if not success then
		log.e("插件启动失败: " .. pluginId .. " - " .. tostring(result))
		return false
	end

	_G.HammerspoonPluginState[pluginId] = result or true
	log.i("插件启动成功: " .. pluginId)
	return true
end

-- 启动显式清单中的插件。
-- 入参：globalConfig 全局配置表。
-- 返回值：成功数量和失败数量。
local function startPlugins(globalConfig)
	local loadedCount = 0
	local errorCount = 0

	for _, pluginId in ipairs(pluginOrder) do
		if startPlugin(pluginId, globalConfig) then
			loadedCount = loadedCount + 1
		else
			errorCount = errorCount + 1
		end
	end

	return loadedCount, errorCount
end

-- 监听 Lua 配置变化并延迟重载。
-- 入参：files 变更文件路径列表。
-- 返回值：无。
local function reloadConfig(files)
	for _, file in pairs(files) do
		if file:sub(-4) == ".lua" then
			hs.timer.doAfter(0.5, function()
				hs.reload()
			end)
			return
		end
	end
end

ensureScriptsDir()

_G.HammerspoonConfig = loadConfig()
_G.HammerspoonPluginState = {}

local loadedCount, errorCount = startPlugins(_G.HammerspoonConfig)

local configWatcher = hs.pathwatcher.new(configDir, reloadConfig)
configWatcher:start()

local scriptsWatcher = hs.pathwatcher.new(scriptsDir, reloadConfig)
scriptsWatcher:start()

local showAlerts = _G.HammerspoonConfig.showAlerts ~= false
if showAlerts then
	hs.alert.show(string.format("Hammerspoon 配置已加载: 成功 %d, 失败 %d", loadedCount, errorCount), 2)
end

log.i(string.format("Hammerspoon 配置加载完成: 成功 %d, 失败 %d", loadedCount, errorCount))
