name: PowerShell Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Run Pester Tests
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4 
    - name: Perform a Pester test 
      shell: pwsh
      run: 
        Invoke-Pester -Configuration (./PesterConfiguration.ps1) 
