#!/usr/bin/env bash
set -Eeuo pipefail

# 构建 systemd-service-manager 的单文件产物。
# 主产物放到仓库根目录 bin/，同时在 scripts/bash 下保留便携副本。

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../../.." && pwd)"
BIN_OUTPUT="${REPO_ROOT}/bin/systemd-service-manager"
LOCAL_OUTPUT="${REPO_ROOT}/scripts/bash/systemd-service-manager.sh"

MODULES=(
  "${SCRIPT_DIR}/common.sh"
  "${SCRIPT_DIR}/lib/cli.sh"
  "${SCRIPT_DIR}/lib/project.sh"
  "${SCRIPT_DIR}/lib/env.sh"
  "${SCRIPT_DIR}/lib/parser-service.sh"
  "${SCRIPT_DIR}/lib/parser-timer.sh"
  "${SCRIPT_DIR}/lib/schedule.sh"
  "${SCRIPT_DIR}/lib/validate.sh"
  "${SCRIPT_DIR}/commands/init.sh"
  "${SCRIPT_DIR}/commands/list.sh"
  "${SCRIPT_DIR}/commands/install.sh"
  "${SCRIPT_DIR}/main.sh"
)

for module in "${MODULES[@]}"; do
  if [[ ! -f "${module}" ]]; then
    printf 'Missing module: %s\n' "${module}" >&2
    exit 1
  fi
done

mkdir -p "$(dirname "${BIN_OUTPUT}")"
mkdir -p "$(dirname "${LOCAL_OUTPUT}")"

TMP_OUTPUT="$(mktemp)"
trap 'rm -f "${TMP_OUTPUT}"' EXIT

{
  printf '#!/usr/bin/env bash\n'
  printf 'set -Eeuo pipefail\n'
  printf '# Auto-generated by scripts/bash/systemd-service-manager/build.sh. Do not edit directly.\n'
  printf 'SSM_STANDALONE=1\n'
  for module in "${MODULES[@]}"; do
    printf '\n# --- %s ---\n' "$(basename "${module}")"
    cat "${module}"
    printf '\n'
  done
} > "${TMP_OUTPUT}"

install -m 0755 "${TMP_OUTPUT}" "${BIN_OUTPUT}"
install -m 0755 "${TMP_OUTPUT}" "${LOCAL_OUTPUT}"

printf 'Built %s\n' "${BIN_OUTPUT}"
printf 'Built %s\n' "${LOCAL_OUTPUT}"
