#!/usr/bin/env bash
set -Eeuo pipefail

# 构建 systemd-service-manager 的单文件产物。
# 主产物放到仓库根目录 bin/，同时在 scripts/bash 下保留便携副本。

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../../.." && pwd)"
BIN_OUTPUT="${REPO_ROOT}/bin/systemd-service-manager"
LOCAL_OUTPUT="${REPO_ROOT}/scripts/bash/systemd-service-manager.sh"

MODULES=(
  "${SCRIPT_DIR}/common.sh"
  "${SCRIPT_DIR}/lib/cli.sh"
  "${SCRIPT_DIR}/lib/project.sh"
  "${SCRIPT_DIR}/lib/env.sh"
  "${SCRIPT_DIR}/lib/parser-service.sh"
  "${SCRIPT_DIR}/lib/parser-timer.sh"
  "${SCRIPT_DIR}/lib/schedule.sh"
  "${SCRIPT_DIR}/lib/render-service.sh"
  "${SCRIPT_DIR}/lib/render-timer.sh"
  "${SCRIPT_DIR}/lib/systemd.sh"
  "${SCRIPT_DIR}/lib/validate.sh"
  "${SCRIPT_DIR}/commands/init.sh"
  "${SCRIPT_DIR}/commands/list.sh"
  "${SCRIPT_DIR}/commands/install.sh"
  "${SCRIPT_DIR}/commands/start.sh"
  "${SCRIPT_DIR}/commands/stop.sh"
  "${SCRIPT_DIR}/commands/restart.sh"
  "${SCRIPT_DIR}/commands/status.sh"
  "${SCRIPT_DIR}/commands/logs.sh"
  "${SCRIPT_DIR}/commands/enable.sh"
  "${SCRIPT_DIR}/commands/disable.sh"
  "${SCRIPT_DIR}/main.sh"
)

for module in "${MODULES[@]}"; do
  if [[ ! -f "${module}" ]]; then
    printf 'Missing module: %s\n' "${module}" >&2
    exit 1
  fi
done

mkdir -p "$(dirname "${BIN_OUTPUT}")"
mkdir -p "$(dirname "${LOCAL_OUTPUT}")"

TMP_OUTPUT="$(mktemp)"
trap 'rm -f "${TMP_OUTPUT}"' EXIT

emit_embedded_templates() {
  local template_name
  local template_path

  printf '\n# --- embedded templates ---\n'
  printf '%s\n' 'ssm_write_embedded_template() {'
  printf '%s\n' '  local template_name="$1"'
  printf '%s\n' '  local destination="$2"'
  printf '%s\n' '  mkdir -p "$(dirname "${destination}")"'
  printf '%s\n' '  case "${template_name}" in'

  for template_name in \
    "README.md" \
    "project.conf.example" \
    "project.env.example" \
    "service.conf.example" \
    "service.env.example" \
    "timer-service.conf.example" \
    "timer-task.conf.example"; do
    template_path="${SCRIPT_DIR}/templates/${template_name}"
    printf "    '%s') cat >\"\${destination}\" <<'SSM_TEMPLATE_EOF'\n" "${template_name}"
    cat "${template_path}"
    printf '\nSSM_TEMPLATE_EOF\n'
    printf '%s\n' '      ;;'
  done

  printf '%s\n' '    *)'
  printf '%s\n' '      return 1'
  printf '%s\n' '      ;;'
  printf '%s\n' '  esac'
  printf '%s\n' '}'
}

{
  printf '#!/usr/bin/env bash\n'
  printf 'set -Eeuo pipefail\n'
  printf '# Auto-generated by scripts/bash/systemd-service-manager/build.sh. Do not edit directly.\n'
  printf 'SSM_STANDALONE=1\n'
  emit_embedded_templates
  for module in "${MODULES[@]}"; do
    printf '\n# --- %s ---\n' "$(basename "${module}")"
    cat "${module}"
    printf '\n'
  done
} > "${TMP_OUTPUT}"

install -m 0755 "${TMP_OUTPUT}" "${BIN_OUTPUT}"
install -m 0755 "${TMP_OUTPUT}" "${LOCAL_OUTPUT}"

printf 'Built %s\n' "${BIN_OUTPUT}"
printf 'Built %s\n' "${LOCAL_OUTPUT}"
